-- Every known RDR2 horse ped model, grouped later at runtime by breed prefix.
HorseModels = {
    "a_c_horse_americanpaint_greyovero",
    "a_c_horse_americanpaint_overo",
    "a_c_horse_americanpaint_splashedwhite",
    "a_c_horse_americanpaint_tobiano",

    "a_c_horse_americanstandardbred_black",
    "a_c_horse_americanstandardbred_buckskin",
    "A_C_Horse_AmericanStandardbred_LightBuckskin",
    "a_c_horse_americanstandardbred_palominodapple",
    "a_c_horse_americanstandardbred_silvertailbuckskin",

    "a_c_horse_andalusian_darkbay",
    "a_c_horse_andalusian_perlino",
    "a_c_horse_andalusian_rosegray",

    "a_c_horse_appaloosa_blacksnowflake",
    "a_c_horse_appaloosa_blanket",
    "a_c_horse_appaloosa_brownleopard",
    "A_C_Horse_Appaloosa_FewSpotted_PC",
    "a_c_horse_appaloosa_leopard",
    "a_c_horse_appaloosa_leopardblanket",

    "a_c_horse_arabian_black",
    "a_c_horse_arabian_grey",
    "A_C_Horse_Arabian_RedChestnut",
    "A_C_Horse_Arabian_RedChestnut_PC",
    "a_c_horse_arabian_rosegreybay",
    "A_C_Horse_Arabian_WarpedBrindle_PC",
    "a_c_horse_arabian_white",

    "a_c_horse_ardennes_bayroan",
    "a_c_horse_ardennes_irongreyroan",
    "a_c_horse_ardennes_strawberryroan",

    "a_c_horse_belgian_blondchestnut",
    "a_c_horse_belgian_mealychestnut",

    "A_C_Horse_Breton_GrulloDun",
    "A_C_Horse_Breton_MealyDappleBay",
    "A_C_Horse_Breton_RedRoan",
    "A_C_Horse_Breton_SealBrown",
    "A_C_Horse_Breton_Sorrel",
    "A_C_Horse_Breton_SteelGrey",

    "a_c_horse_buell_warvets",

    "A_C_Horse_Criollo_BayBrindle",
    "A_C_Horse_Criollo_BayFrameOvero",
    "A_C_Horse_Criollo_BlueRoanOvero",
    "A_C_Horse_Criollo_Dun",
    "A_C_Horse_Criollo_MarbleSabino",
    "A_C_Horse_Criollo_SorrelOvero",

    "a_c_horse_dutchwarmblood_chocolateroan",
    "a_c_horse_dutchwarmblood_sealbrown",
    "a_c_horse_dutchwarmblood_sootybuckskin",

    "a_c_horse_eagleflies",

    "a_c_horse_gang_bill",
    "a_c_horse_gang_charles",
    "a_c_horse_gang_charles_endlesssummer",
    "a_c_horse_gang_dutch",
    "a_c_horse_gang_hosea",
    "a_c_horse_gang_javier",
    "a_c_horse_gang_john",
    "a_c_horse_gang_karen",
    "a_c_horse_gang_kieran",
    "a_c_horse_gang_lenny",
    "a_c_horse_gang_micah",
    "a_c_horse_gang_sadie",
    "a_c_horse_gang_sadie_endlesssummer",
    "a_c_horse_gang_sean",
    "a_c_horse_gang_trelawney",
    "a_c_horse_gang_uncle",
    "a_c_horse_gang_uncle_endlesssummer",

    "a_c_horse_gypsycob_palominoblagdon",
    "a_c_horse_gypsycob_piebald",
    "a_c_horse_gypsycob_skewbald",
    "a_c_horse_gypsycob_splashedbay",
    "a_c_horse_gypsycob_splashedpiebald",
    "a_c_horse_gypsycob_whiteblagdon",

    "a_c_horse_hungarianhalfbred_darkdapplegrey",
    "a_c_horse_hungarianhalfbred_flaxenchestnut",
    "a_c_horse_hungarianhalfbred_liverchestnut",
    "a_c_horse_hungarianhalfbred_piebaldtobiano",

    "a_c_horse_john_endlesssummer",

    "a_c_horse_kentuckysaddle_black",
    "A_C_HORSE_KENTUCKYSADDLE_ButtermilkBuckskin_PC",
    "a_c_horse_kentuckysaddle_chestnutpinto",
    "a_c_horse_kentuckysaddle_grey",
    "a_c_horse_kentuckysaddle_silverbay",

    "A_C_Horse_Kladruber_Black",
    "A_C_Horse_Kladruber_Cremello",
    "A_C_Horse_Kladruber_DappleRoseGrey",
    "A_C_Horse_Kladruber_Grey",
    "A_C_Horse_Kladruber_Silver",
    "A_C_Horse_Kladruber_White",

    "a_c_horse_missourifoxtrotter_amberchampagne",
    "a_c_horse_missourifoxtrotter_blacktovero",
    "a_c_horse_missourifoxtrotter_blueroan",
    "a_c_horse_missourifoxtrotter_buckskinbrindle",
    "a_c_horse_missourifoxtrotter_dapplegrey",
    "a_c_horse_missourifoxtrotter_sablechampagne",
    "a_c_horse_missourifoxtrotter_silverdapplepinto",

    "a_c_horse_morgan_bay",
    "a_c_horse_morgan_bayroan",
    "a_c_horse_morgan_flaxenchestnut",
    "A_C_HORSE_Morgan_LiverChestnut_PC",
    "a_c_horse_morgan_palomino",

    "A_C_Horse_MP_Mangy_Backup",

    "a_c_horse_murfreebrood_mange_01",
    "a_c_horse_murfreebrood_mange_02",
    "a_c_horse_murfreebrood_mange_03",

    "a_c_horse_mustang_blackovero",
    "a_c_horse_mustang_buckskin",
    "a_c_horse_mustang_chestnuttovero",
    "a_c_horse_mustang_goldendun",
    "a_c_horse_mustang_grullodun",
    "a_c_horse_mustang_reddunovero",
    "a_c_horse_mustang_tigerstripedbay",
    "a_c_horse_mustang_wildbay",

    "a_c_horse_nokota_blueroan",
    "a_c_horse_nokota_reversedappleroan",
    "a_c_horse_nokota_whiteroan",

    "A_C_HORSE_NORFOLKROADSTER_BLACK",
    "A_C_HORSE_NORFOLKROADSTER_DAPPLEDBUCKSKIN",
    "A_C_HORSE_NORFOLKROADSTER_PIEBALDROAN",
    "A_C_HORSE_NORFOLKROADSTER_ROSEGREY",
    "A_C_HORSE_NORFOLKROADSTER_SPECKLEDGREY",
    "A_C_HORSE_NORFOLKROADSTER_SPOTTEDTRICOLOR",

    "a_c_horse_shire_darkbay",
    "a_c_horse_shire_lightgrey",
    "a_c_horse_shire_ravenblack",

    "a_c_horse_suffolkpunch_redchestnut",
    "a_c_horse_suffolkpunch_sorrel",

    "a_c_horse_tennesseewalker_blackrabicano",
    "a_c_horse_tennesseewalker_chestnut",
    "a_c_horse_tennesseewalker_dapplebay",
    "a_c_horse_tennesseewalker_flaxenroan",
    "A_C_Horse_TennesseeWalker_GoldPalomino_PC",
    "a_c_horse_tennesseewalker_mahoganybay",
    "a_c_horse_tennesseewalker_redroan",

    "a_c_horse_thoroughbred_blackchestnut",
    "a_c_horse_thoroughbred_bloodbay",
    "a_c_horse_thoroughbred_brindle",
    "a_c_horse_thoroughbred_dapplegrey",
    "a_c_horse_thoroughbred_reversedappleblack",

    "a_c_horse_turkoman_black",
    "a_c_horse_turkoman_chestnut",
    "a_c_horse_turkoman_darkbay",
    "a_c_horse_turkoman_gold",
    "a_c_horse_turkoman_grey",
    "a_c_horse_turkoman_perlino",
    "a_c_horse_turkoman_silver",

    "a_c_horse_winter02_01",

    "A_C_HorseMule_01",
    "A_C_HorseMulePainted_01",
    "A_C_Donkey_01",
}
