Locales['en'] = {
    -- แปลเมนูบริการสังคม (Community Service Menu)
    jailchoreblip = 'Prison Work',
    communityseviceblip = 'Social Services',
    presstodotask = "Press 'E' to start working.",
    choosechore = 'เลือกงานที่ต้องทำ: ',
    amountofchores = 'จำนวนงานที่ต้องทำ: ',
    giveservice = 'มอบหมายงานบริการสังคม',
    servicemenu = 'เมนูบริการสังคม',
    choretype = 'งานก่อสร้าง',

    -- แปลเมนูป้อนข้อมูล (Input Menu)
    inputconfirm = 'ยืนยัน',
    playerid = 'รหัสผู้เล่น: ',
    fineamount = 'จำนวนค่าปรับ: ',
    jailamount = 'ระยะเวลาจำคุก: ',
    numberonly = 'กรอกได้เฉพาะตัวเลข',


    --Menu Translates
    lawmenu = 'เมนูกฎหมาย',
    searchplayer = 'ค้นตัวประชาชน',
    togglebadge = 'แสดง/ซ่อนตราตำรวจ',
    cufftoggle = 'ใส่/ปลดกุญแจมือประชาชน',
    escort = 'ควบคุมตัวผู้ถูกใส่กุญแจมือ',
    fineplayer = 'ออกใบสั่งปรับประชาชน',
    jailplayer = 'นำประชาชนเข้าคุก',
    serviceplayer = 'มอบหมายงานบริการชุมชน',
    grabammo = "รับกระสุน",
    grabweapons = "รับอาวุธ",
    Cabinet = "ตู้เก็บของ",
    putinoutvehicle = 'นำขึ้น/ลงจากเกวียน',
    inventorytitle = "กระเป๋าสัมภาระของประชาชน",

    -- แปลเมนูค่าปรับ (Fine Menu)
    bill = "ออกใบเรียกเก็บเงิน (Syn_Society)",
    billdesc = 'ออกใบเรียกเก็บเงินให้ประชาชน โดยให้สามารถชำระเงินภายหลังเข้าบัญชีกลุ่ม',
    fine = 'ค่าปรับ (ปกติ)',
    finedesc = 'ออกค่าปรับให้ประชาชน หักเงินสดของประชาชนทันทีและนำเข้าบัญชีกลุ่ม',

    -- แปลเมนูบัตรประชาชน (ID Menu)
    idmenu = 'เมนูบัตรประชาชน',
    citizenid = "ขอดูบัตรประชาชน",
    horseowner = "ตรวจสอบเจ้าของม้า",
    horseownerdesc = "ตรวจสอบเจ้าของม้า หากเจ้าของไม่อยู่ใกล้ ๆ จะแสดงว่าไม่มีเจ้าของ",

    -- แปลเมนูค้นตัว (Search Menu)
    searchmenu = 'เมนูค้นตัว',
    playermoney = 'เงินสด: ',
    checkitems = 'ตรวจสอบไอเท็ม',
    checkweapons = 'ตรวจสอบอาวุธ',

    -- แปลเมนูคุก (Jail Menu)
    Autotele = "ส่งเข้าคุกอัตโนมัติ: ",
    Autoteledesc = "ประชาชนควรถูกนำตัวไปคุกอัตโนมัติ หรือเจ้าหน้าที่ต้องพาไปเอง",
    jaillocaiton = "สถานที่คุมขัง: ",
    jail = "ขังคุกประชาชน",
    jaildesc = 'หากการส่งเข้าคุกอัตโนมัติถูกปิด เจ้าหน้าที่ต้องพาผู้ต้องหาไปเอง มิฉะนั้น NPC จะเป็นคนพาไป',
    unjail = "ปล่อยตัวประชาชนตาม ID ที่กำหนด",
    jailmenu = "เมนูคุก",

    --Jail Locations
    valjail = "Valentine Sheriff Office",
    bwjail = "Blackwater Sheriff Office",
    tujail = "Tumbleweed Sheriff Office",
    stjail = "Strawberry Sheriff Office",
    sdjail = "Saint Denis Sheriff Office",
    anjail = "Annesburg Sheriff Office",
    arjail = "Armadillo Sheriff Office",
    rhjail = 'Rhodes Sheriff Office',
    sisika = 'Sisika Prison',
    --Notify Translates
    badgeon = 'You put your badge on',
    badgeoff = 'You took your badge off',
    notcloseenough = 'Not close enough to a citizen',
    notcloseenoughtowagon = 'Not close enough to a wagon',
    jailbreak = 'You have been broken out from prison. Now Run!',
    onduty = 'You are already on Duty',
    imprisoned = 'You are imprisoned for: ',
    minutes = ' minutes',
    jailseconds = ' seconds remaining',
    released = "You have been released from prison. Now straighten up and fly right!",
    youhave = "You have ",
    secondsremaining = ' seconds remaining to return before being jailed',
    crimereported = 'Crime Reported',
    jailbreakalert = "A Jail Break has been reported, check you map for a location",
    goonduty = 'You are now on Duty',
    nottherightjob = "You do not have the right job",
    gooffduty = 'You are now off Duty',
    youfined = 'You fined ',
    currency = '$',
    recievedfine = 'You received a fine of $',
    givenservice = 'You have been given Community Service',
    idcheck = 'ID Check',
    name = 'Name: ',
    job = 'Job: ',
    notowned = "Horse not owned by anyone",
    taskfailed = 'Task Failed',
    servicecomplete = 'Community Service Completed, straighten up!',
    lockpickbroke = "Gosh Darnit! My Lockpick broke!",
    jailed = "You have been jailed for breaking Community Service, straighten up",
    outofroom = "You are out of room",
    notcuffed = "Citizen is not cuffed",
    --Webhook Translates
    sentto = ' sent ',
    tojailfor = ' to jail for ',
    seconds = ' seconds ',
    gaveservice = ' gave ',
    ofchores = ' chores ',
    unjailed = ' unjailed ',
    gaveafine = ' gave a fine of $',
    to = ' to ',
    took = ' took ',
    of = ' of ',
    from = ' from ',
    --Misc Translates
    none = 'None',
    varfalse = 'false',
    vartrue = 'true',
    opencabinet = 'Open Cabinet',
    search = 'Search',
    invalid = ' invalid ',
    --Badge Translates
    up = "Move Badge Up",
    left = "Move Badge Left",
    right = "Move Badge Right",
    down = "Move Badge Down",
    sisika_commisary = 'Press "G" to get some food and water.',
    youarenotonduty ='you are not on duty',
    nocuffs = 'you dont have any handcuffs'
}
