local VORPcore = exports.vorp_core:GetCore()
local VorpInv = exports.vorp_inventory:vorp_inventoryApi()

local UsedCodesFile = "core/used_codes.json"
local UsedCodes = {}
local generatedRandomCodes = {}  -- codes generated by admin at runtime

local redeemCooldowns = {}
local randomCodeCooldowns = {}

local function checkCooldown(tbl, src, ms)
    local t = GetGameTimer()
    if tbl[src] and (t - tbl[src]) < ms then return false end
    tbl[src] = t
    return true
end

AddEventHandler('playerDropped', function()
    redeemCooldowns[source] = nil
    randomCodeCooldowns[source] = nil
end)

-- High: isAdmin uses getGroup() method correctly, not property
local function isAdmin(playerId)
    if playerId == 0 then return true end
    local user = VORPcore.getUser(playerId)
    if not user then return false end
    local group = (type(user.getGroup) == 'function' and user.getGroup()) or user.group or ''
    return group == Config.AdminGroup
end

local function SaveUsedCodes()
    local ok, encoded = pcall(json.encode, UsedCodes)
    if ok and encoded then
        SaveResourceFile(GetCurrentResourceName(), UsedCodesFile, encoded, -1)
    else
        print("^1[ERROR]^0 JSON encode ผิดพลาด")
    end
end

local function LoadUsedCodes()
    local content = LoadResourceFile(GetCurrentResourceName(), UsedCodesFile)
    if content and content ~= "" then
        local success, result = pcall(json.decode, content)
        if success and result then
            UsedCodes = result
        else
            UsedCodes = {}
            SaveUsedCodes()
        end
    else
        UsedCodes = {}
        SaveUsedCodes()
    end
end

local function convertToTimestamp(dateStr)
    return os.time({
        year  = tonumber(dateStr:sub(1, 4)),
        month = tonumber(dateStr:sub(6, 7)),
        day   = tonumber(dateStr:sub(9, 10)),
        hour  = tonumber(dateStr:sub(12, 13)),
        min   = tonumber(dateStr:sub(15, 16)),
        sec   = tonumber(dateStr:sub(18, 19))
    })
end

-- High: isWithinTimeWindow now wired into redeemRewardCode
local function isWithinTimeWindow()
    local now   = os.time()
    local start = convertToTimestamp(Config.CodeTimeWindow.Starttime)
    local stop  = convertToTimestamp(Config.CodeTimeWindow.Endtime)
    return now >= start and now <= stop
end

local function giveReward(src, reward)
    local user = VORPcore.getUser(src)
    if not user then return end
    -- getUsedCharacter เป็น property (table ตัวละครโดยตรง) ไม่ใช่ function — ห้ามใส่ ()
    -- (vorp_core/server/class/user.lua: userData.getUsedCharacter = self.UsedCharacter() ตั้งไว้ล่วงหน้าแล้ว)
    local char = user.getUsedCharacter

    if reward.items then
        for _, item in pairs(reward.items) do
            -- Medium: addItem with callback to detect failure
            exports.vorp_inventory:addItem(tostring(src), item.name, item.count, nil, function(success)
                if not success then
                    print("^1[ERROR]^0 addItem failed: " .. tostring(item.name) .. " for src " .. tostring(src))
                end
            end)
        end
    end

    if reward.money and char then
        char.addCurrency(0, tonumber(reward.money))
    end

    if reward.weapon then
        VorpInv:createWeapon(tostring(src), reward.weapon, reward.weapon_ammo or 0, nil)
    end
end

-- Admin command: open UI with correct admin flag
RegisterCommand(Config.AdminCommand, function(source, args, rawCommand)
    TriggerClientEvent("openCodeUI", source, isAdmin(source))
end, false)

RegisterServerEvent('redeemRewardCode')
AddEventHandler('redeemRewardCode', function(code)
    local src = source
    if not checkCooldown(redeemCooldowns, src, 3000) then return end
    if type(code) ~= 'string' or #code == 0 or #code > 64 then return end

    -- High: enforce time window
    if not isWithinTimeWindow() then
        TriggerClientEvent("redeemCodeResult", src, false, "Code redemption is not available at this time.")
        return
    end

    -- Medium: nil guard before getUsedCharacter
    local user = VORPcore.getUser(src)
    if not user then return end
    -- getUsedCharacter เป็น property ไม่ใช่ function — ใส่ () แล้ว error "attempt to call
    -- a table value" ทุกครั้ง (server console เท่านั้น ผู้เล่นไม่เห็น) ทำให้ redeemCodeResult
    -- ไม่ถูกส่งกลับไปเลย นี่คือสาเหตุที่กด Enter แล้วดูเหมือนไม่มีอะไรเกิดขึ้น
    local xPlayer = user.getUsedCharacter
    if not xPlayer then
        print("^1[ERROR]^0 ผู้เล่นไม่พบ!")
        return
    end
    local identifier = xPlayer.identifier

    if UsedCodes[identifier] and UsedCodes[identifier][code] then
        TriggerClientEvent("redeemCodeResult", src, false, "This code has already been used!")
        return
    end

    -- preset codes
    if Config.RewardCodes[code] then
        giveReward(src, Config.RewardCodes[code])
        UsedCodes[identifier] = UsedCodes[identifier] or {}
        UsedCodes[identifier][code] = true
        SaveUsedCodes()
        TriggerClientEvent("redeemCodeResult", src, true, "Code redeemed! Reward delivered.")
        return
    end

    -- High: use generatedRandomCodes map (was Config.RandomCodes string lookup — wrong type)
    if generatedRandomCodes[code] and #Config.RandomCodes > 0 then
        local reward = Config.RandomCodes[math.random(1, #Config.RandomCodes)]
        giveReward(src, reward)
        UsedCodes[identifier] = UsedCodes[identifier] or {}
        UsedCodes[identifier][code] = true
        generatedRandomCodes[code] = nil  -- single-use
        SaveUsedCodes()
        TriggerClientEvent("redeemCodeResult", src, true, "Code redeemed! Reward delivered.")
        return
    end

    print("^1[ERROR]^0 โค้ดไม่ถูกต้อง! (" .. tostring(code) .. ")")
    TriggerClientEvent("redeemCodeResult", src, false, "Invalid code or cannot be used.")
end)

-- Critical: isAdmin check + cooldown — any client could trigger this before
RegisterServerEvent("getRandomRewardCode")
AddEventHandler("getRandomRewardCode", function(newCode)
    local src = source
    if not isAdmin(src) then return end
    if not checkCooldown(randomCodeCooldowns, src, 2000) then return end
    if type(newCode) ~= 'string' or #newCode == 0 or #newCode > 64 then return end
    generatedRandomCodes[newCode] = true
end)

Citizen.CreateThread(function()
    Citizen.Wait(1000)
    LoadUsedCodes()
    print("^2[INFO]^0 MJ-CodeReward: โหลดข้อมูลโค้ดสำเร็จ")
end)
